# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Demo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'beachhead', :git => 'https://github.com/forwyt/beachhead.git',:tag => '0.1.0'

end
